steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "southamerica-east1-docker.pkg.dev/palpitacojb-app/palpitaco-jobs/auto-import:56963685e1ca"
      - "."
images:
  - "southamerica-east1-docker.pkg.dev/palpitacojb-app/palpitaco-jobs/auto-import:56963685e1ca"
serviceAccount: "projects/palpitacojb-app/serviceAccounts/palpitaco-build@palpitacojb-app.iam.gserviceaccount.com"
options:
  logging: CLOUD_LOGGING_ONLY